// swift-tools-version: 5.7

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "AnGitMoji",
    platforms: [
        .iOS("16.0"),
        .macOS("13.0")
    ],
    products: [
        .iOSApplication(
            name: "AnGitMoji",
            targets: ["AnGitMoji"],
            bundleVersion: "1",
            appIcon: .placeholder(icon: .cat),
            accentColor: .presetColor(.purple),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: .utilities
        ),
        .library(
            name: "AnGitMojiCore",
            type: .dynamic,
            targets: ["AnGitMojiCore"]
        )
    ],
    targets: [
        .executableTarget(
            name: "AnGitMoji"
        ),
        .target(
            name: "AnGitMojiCore"
        ),
        .testTarget(
            name: "AnGitMojiCoreTests",
            dependencies: [
                "AnGitMojiCore"
            ]
        )
    ]
)
